2024-FinalProject/AIHOPS

AIHOPS/Front/src/Components/Histogram.jsx

Fixing Histogram graph - showing incorrect values per factor - mismatching

---

AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/Histogram.jsx

Now the data can be refreshed (fetched from the backend) without exiting and entering the analyze projects result section.

Refresh button for analyze page

---

AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/Histogram.jsx
AIHOPS/Front/src/Pages/MyProjects.jsx

Now when voting on a single factor (or some of them, but not all of them) - when the voter has previously completed the voting on the factors (hence voted on all of them) - it'll still display as completed.

Voting on single factor update fix

---

AIHOPS/Front/src/Components/EditPopup.jsx

Edited the message display in manage assessors in project management page. 
The message is being displayed only when inviting a new member now, and the message itself is now shorter and clearer.

Message display in assessors invitation section

---

AIHOPS/Front/src/Components/NavBar.css
AIHOPS/Front/src/Components/NavBar.jsx

Implemented a notification alert for the Notifications section in the Nav-Bar - now it is visible from the nav-bar that the user has new notifications.

Added a Notification Alert to the Nav-Bar

---

AIHOPS/Front/src/Components/EditPopup.css
AIHOPS/Front/src/Components/EditPopup.jsx
AIHOPS/Front/src/Components/ProjectStatusPopup.css

Worked on the Content Factors display pop-up page. Improved & changed the layout.

Content Factors Page display - changed layout 

---

AIHOPS/Front/src/Components/EditPopup.css
AIHOPS/Front/src/Components/EditPopup.jsx
AIHOPS/Front/src/Components/ProgressBar.css
AIHOPS/Front/src/Components/ProgressBar.jsx
AIHOPS/Front/src/Components/ProjectStatusPopup.jsx

1. Removed the Projects Actions and moved them into the Progress Bar, which is now clickable.
2. Added a more enhanced styling and changed the ProgressBar layout.
3. Added the 'Unset' reminder to the ProgressBar page.

149 ProgressBar Update

---

AIHOPS/Front/src/Components/FactorVotingModal.css
AIHOPS/Front/src/Components/FactorVotingModal.jsx
AIHOPS/Front/src/Components/ProjectStatusPopup.jsx
AIHOPS/Front/src/Pages/MyProjects.jsx

Fixed a lot of bugs and visuality of the FactorVotingModal page - for example: didn't call any voting logic in the backend...

Bug, Logic & Visuality fixing in FactorVotingModal page.

---

AIHOPS/Front/src/Components/EditPopup.jsx
AIHOPS/Front/src/Components/FactorVotingModal.css
AIHOPS/Front/src/Components/ProjectStatusPopup.css
AIHOPS/Front/src/Pages/MyProjects.jsx

1. Fixed an issue with addition of a new factor - updating factors_inited field.
2. Changed a bit of coloring and spacing in the FactorVotingModal & MyProjects pages.
3. Fixed a bug with fetching a selected project in the ProjectStatusPop Page.

Add dimension navigation fix & fetching selected project bug fix

---

AIHOPS/Front/src/Components/FactorVotingModal.css
AIHOPS/Front/src/theme.css

Worked on the dark theme for the voting on project factors pop-up page, looks better now.

Dark Theme in the Voting on Project Factors pop-up page.

---

AIHOPS/Front/src/Components/VotingTypeSelector.css
AIHOPS/Front/src/Components/VotingTypeSelector.jsx

Added an empty box & 'V' sign inside of the box for vote indication in the VotingTypeSelector pop-up page.

VotingTypeSelector pop-up page: Visual Voting Indication 

---

AIHOPS/Front/src/Components/AnalyzeResult.jsx

added factor weights
some visual changes

174 analyze result with factor weights

---

AIHOPS/Front/src/Components/Histogram.jsx

Removed the title from the tool-tip hover-over pop-up window.
Only shows average score & std dev now.

Removed the title from the tool-tip hover-over pop-up window.

---

AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/Histogram.jsx

Fixed an issue with the display of Assessment Dimensions in analyze result graph - x-axis names wouldn't be rendered

Fixed an issue with the display of Assessment Dimensions rendering (in Analyze Result pop-up)

---

AIHOPS/Front/src/Components/EditPopup.jsx

Changed all occurrences of 'member' to 'assessor' in the Manage Assessors pop-up page in the EditPopup.jsx file

'Member' changed to 'Assessor' in Manage Assessors pop-up page

---

AIHOPS/Front/package-lock.json
AIHOPS/Front/package.json
AIHOPS/Front/src/Components/EditPopup.jsx

Implemented valid email checking in the front (before sending the info to the backend) in the Manage Assessors pop-up page. 
By using email-validator (react) library.

Email verification in Manage Assessors page

---

AIHOPS/Front/src/Components/EditPopup.jsx

Changed basic alert's to the more complex AlertPopup.jsx component. Also fixed the synchronization of the 'confirm severity factors' delay (was missing an 'await' before the call).

Basic alert's changed to AlertPopUp component (in the EditPopUp.jsx page)

---

AIHOPS/DAL/Objects/DBMember.py
AIHOPS/Domain/src/Server.py
AIHOPS/Domain/src/Users/Member.py
AIHOPS/Domain/src/Users/MemberController.py
AIHOPS/Domain/src/Users/User.py
AIHOPS/Front/package-lock.json
AIHOPS/Front/package.json
AIHOPS/Front/src/App.jsx
AIHOPS/Front/src/Pages/Login.css
AIHOPS/Front/src/Pages/Login.jsx
AIHOPS/Front/src/api/AuthApi.jsx
AIHOPS/Service/ServiceServer.py

Implemented Gmail auth login - seems to be working well but has an issue related to the terms & conditions acceptance - should be a backend logic, currently being as a session local storage logic in the front, will need to change that

Gmail Auth Login

---

AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/CreateProjectPopup.jsx
AIHOPS/Front/src/Components/EditPopup.css
AIHOPS/Front/src/Components/EditPopup.jsx
AIHOPS/Front/src/Components/ProgressBar.css
AIHOPS/Front/src/Components/ProgressBar.jsx
AIHOPS/Front/src/Components/PublishingModal.css
AIHOPS/Front/src/theme.css

1. Fixed the spinner animation (being too big) in the PublishingModal component.
2. Made the header sections of the same syntactic type - in the ProgressBar.jsx page.
3. Made a visible border between the sections in the progress bar. 
4. Made the publish button to appear in the same section as the design project (instead of in its own section). 
5. Made the section of data analysis & progress bar's to appear grey-ish and unclickable if the project hasn't been published.
6. Changed 'unset' to 'unconfirmed'.
7. Split each section into its own block and made some visual changes to the content.
8. Made the Next/Previous buttons to be visible only if needed - instead of unclickable.
9. Removed the '?' from 'use default factors' in project creation & in 'update all projects in design' from …

Changes in project management page and sub pages - DO NOT APPROVE YET!

---

AIHOPS/Front/src/Components/AnalyzeResult.css
AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/EditPopup.css

Made a more enhanced nav-bar for the analyze result page & fixed the loading spinner position (also improved the jsx page logic regarding the spinner

Analyze Result Page changes

---

AIHOPS/Front/src/Components/EditPopup.css

Changed background color of not active buttons to grey, for better distinction

Analyze Result nav-bar minor change

---

AIHOPS/Front/src/Components/AdminComponents/factors/EditFactor.jsx
AIHOPS/Front/src/Components/EditPopup.jsx
AIHOPS/Front/src/Components/FactorInputForm.jsx

Limited the dimension assessment's name to a max length of 50

Limited the dimension assessment's name length

---

AIHOPS/DAL/DBAccess.py
AIHOPS/Domain/src/ProjectModule/ProjectManager.py
AIHOPS/Domain/src/Server.py
AIHOPS/Domain/src/Users/MemberController.py
AIHOPS/Front/src/Pages/Settings.jsx
AIHOPS/Front/src/api/AuthApi.jsx
AIHOPS/Service/ServiceServer.py

Account Deletion

---

AIHOPS/Front/src/Components/FactorVotingModal.css
AIHOPS/Front/src/Components/FactorVotingModal.jsx

Changed voting color to purple in the nav-bar & gradient colors in the voting itself.

Coloring in voting page.

---

AIHOPS/Front/src/Components/EditPopup.css
AIHOPS/Front/src/Components/NavBar.css
AIHOPS/Front/src/Components/NavBar.jsx

Fixed nav-bar background color, notifications bell sign aligning and analyze result css color enforcement for the nav-bar there

UI Fixes for Nav Bar & Analyze Result nav-bar component

---

AIHOPS/Domain/src/ProjectModule/Project.py
AIHOPS/Front/src/Pages/ProjectsManagement.jsx

Changed publication to be allowed without assessors invitation - with an appropriate message being displayed

Changed publication to be allowed without assessors invitation (with a warning display)

---

AIHOPS/Domain/src/Users/terms_and_conditions/terms_and_conditions_v1
AIHOPS/Domain/src/Users/terms_and_conditions/terms_and_conditions_v2
AIHOPS/Front/src/Components/AdminComponents/Projects/ProjectsManager.jsx
AIHOPS/Front/src/Components/AnalyzeResult.jsx
AIHOPS/Front/src/Components/ExportCSVButton.jsx
AIHOPS/Front/src/Components/ProjectsView.jsx
AIHOPS/Front/src/Components/getProjectsInfo.jsx
AIHOPS/Front/src/utils/exportProjectToExcel.js
AIHOPS/Front/src/utils/fetchAllProjectData.js
AIHOPS/Front/src/utils/getProjectInfo.js
AIHOPS/Front/src/utils/getProjectScore.js
AIHOPS/Service/ServiceServer.py

researcher can now download multiple csvs
extracted fetching project data and export functionality into js utils files
added useSelectable in projectview
and outside access t projectviews filtered projects

Research multiple csv download

---

AIHOPS/Front/src/Components/EditPopupComponents/FactorsListComponent.jsx
AIHOPS/Front/src/Components/EditPopupComponents/ManageAssessorsComponent.jsx
AIHOPS/Front/src/Pages/ProjectsManagement.jsx
AIHOPS/Front/src/utils/getProjectScore.js

Small fixes to publication confirmation message and alert for fetching an empty score for project

Small fixes in front: 22-05-25
